### ISSUE TITLE
При попытке выполнить install вылетает с ошибкой

### ISSUE THREAD

**Issue by iketari** [mailru/jam#9]
repositories checking "jquery"
repositories checking "accounting"
repositories checking "jquery-ui"
repositories checking "events"
repositories checking "async"
repositories checking "text"
repositories checking "json"
repositories checking "handlebars"
repositories checking "toolkit-common"
repositories checking "ajs"
repositories checking "jquery"

Error: TypeError: Invalid Version: 1.9.0pre
    at new SemVer (/usr/local/lib/node_modules/jamjs/node_modules/semver/semver.js:295:11)
    at Range.test (/usr/local/lib/node_modules/jamjs/node_modules/semver/semver.js:1049:15)
    at Function.satisfies (/usr/local/lib/node_modules/jamjs/node_modules/semver/semver.js:1098:16)
    at /usr/local/lib/node_modules/jamjs/lib/versions.js:71:20
    at Array.every (native)
    at Object.exports.satisfiesAll (/usr/local/lib/node_modules/jamjs/lib/versions.js:62:19)
    at /usr/local/lib/node_modules/jamjs/lib/versions.js:47:24
    at Array.filter (native)
    at Object.exports.maxSatisfying (/usr/local/lib/node_modules/jamjs/lib/versions.js:46:31)
    at /usr/local/lib/node_modules/jamjs/lib/tree.js:163:41
Error: TypeError: Invalid Version: 1.9.0pre
    at new SemVer (/usr/local/lib/node_modules/jamjs/node_modules/semver/semver.js:295:11)
    at Range.test (/usr/local/lib/node_modules/jamjs/node_modules/semver/semver.js:1049:15)
    at Function.satisfies (/usr/local/lib/node_modules/jamjs/node_modules/semver/semver.js:1098:16)
    at /usr/local/lib/node_modules/jamjs/lib/versions.js:71:20
    at Array.every (native)
    at Object.exports.satisfiesAll (/usr/local/lib/node_modules/jamjs/lib/versions.js:62:19)
    at /usr/local/lib/node_modules/jamjs/lib/versions.js:47:24
    at Array.filter (native)
    at Object.exports.maxSatisfying (/usr/local/lib/node_modules/jamjs/lib/versions.js:46:31)
    at /usr/local/lib/node_modules/jamjs/lib/tree.js:163:41
Failed

**Comment by iketari** [comment]
```javascript
{
  "name": "toolkit.mail.ru",
  "description": "Viewer for Toolkit",
  "version": "0.0.1",
  "author": "Burlak Ilia <i.buralk@corp.mail.ru>",
  "maintainers": [
    {
      "name": "Burlak Ilia",
      "url": "https://github.com/burlakilia"
    }
  ],
  "dependencies": {
    "bem": "git+ssh://git@gitlab.corp.mail.ru:mail/bem-tools.git#toolkit",
    "inherit": "2.2.2",
    "vow": "0.3.13",
    "fest": "0.8.2",
    "stylus": "0.32.1",
    "sax": "0.5.4",
    "glob": "*",
    "esprima": "*",
    "xml2js": "*",
    "async": "*",
    "extend": "*",
    "express": "*",
    "request": "*",
    "ejs": "*",
    "restify": "*",
    "quip": "*",
    "node-sass": "0.9.6",
    "chokidar": "*",
    "gulp-sass": "^1.2.2",
    "object-hash": "*",
    "toolkit-bem": "git+ssh://git@gitlab.corp.mail.ru:mail/toolkit-bem.git"
  },
  "engines": {
    "node": ">= 0.8.0"
  },
  "jam": {
    "baseUrl": "./public/app/",
    "packageDir": "./public/app/packages/",
    "dependencies": {
      "jquery": "1.8.3",
      "accounting": "*",
      "jquery-ui": "*",
      "events": "0.0.2",
      "async": ">0.1.22",
      "text": "*",
      "json": "*",
      "handlebars": "*",
      "toolkit-common": "0.0.2",
      "ajs": "0.13.0",
      "url": "0.6.7-kanso.1"
    }
  },
  "devDependencies": {
    "grunt-sass": "~0.17.0",
    "grunt": "~0.4.5",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-concurrent": "~1.0.0",
    "grunt-shell": "~1.1.1",
    "grunt-bem": "0.1.0",
    "debug": "~2.1.1",
    "jamjs": "0.3.0",
    "enb": "0.15.0",
    "enb-bem-techs": "1.0.4",
    "grunt-enb": "0.1.2"
  }
}
```

**Comment by iketari** [comment]
```bash
$ cat ~/.jamrc 
exports.repositories = [ 
    { 
        url: "http://dragonballs.dev.mail.ru:5984/jam-packages", 
        search: false 
    }, 
    "http://jamjs.org/repository" 
];
```
